---
name: WWW-Contact
version: 0.17
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: Get contacts/addressbook from Web
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Crypt::SSLeay: 0
  HTML::TokeParser::Simple: 0
  Moose: 0
  Test::More: 0
  WWW::Mechanize: 0
  WWW::Mechanize::GZip: 0
provides:
  WWW::Contact:
    file: lib/WWW/Contact.pm
    version: 0.17
  WWW::Contact::AOL:
    file: lib/WWW/Contact/AOL.pm
    version: 0.16
  WWW::Contact::Base:
    file: lib/WWW/Contact/Base.pm
    version: 0.16
  WWW::Contact::CN::163:
    file: lib/WWW/Contact/CN/163.pm
    version: 0.16
  WWW::Contact::Gmail:
    file: lib/WWW/Contact/Gmail.pm
    version: 0.17
  WWW::Contact::Hotmail:
    file: lib/WWW/Contact/Hotmail.pm
    version: 0.16
  WWW::Contact::Indiatimes:
    file: lib/WWW/Contact/Indiatimes.pm
    version: 0.16
  WWW::Contact::Lycos:
    file: lib/WWW/Contact/Lycos.pm
    version: 0.16
  WWW::Contact::Mail:
    file: lib/WWW/Contact/Mail.pm
    version: 0.16
  WWW::Contact::Plaxo:
    file: lib/WWW/Contact/Plaxo.pm
    version: 0.16
  WWW::Contact::Rediffmail:
    file: lib/WWW/Contact/Rediffmail.pm
    version: 0.16
  WWW::Contact::Yahoo:
    file: lib/WWW/Contact/Yahoo.pm
    version: 0.16
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
