--- #YAML:1.0
name:                WWW-Contact
version:             0.02
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Crypt::SSLeay:                 0
    HTML::TokeParser::Simple:      0
    Moose:                         0
    Test::More:                    0
    WWW::Mechanize:                0
    WWW::Mechanize::GZip:          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
