--- #YAML:1.0
name:               WWW-Contact
version:            0.37
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Crypt::SSLeay:        0
    HTML::Entities:       0
    HTML::TokeParser::Simple:  0
    HTML::TreeBuilder:    0
    JSON::XS:             0
    Moose:                0.77
    Net::Google::AuthSub:  0
    Test::More:           0
    Text::vCard::Addressbook:  0
    WWW::Mechanize:       0
    WWW::Mechanize::GZip:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
